SERVICE_ACCOUNT_FILE = 'credentials/credenciais_sheets.json'
SPREADSHEET_ID = '1HVlgRHzBjLS4yO9bOKrTeJwlitn9u40CU1rSFwH4VZo'
AGE_NAMED_RANGE = 'df_by_age'
PLATFORM_NAMED_RANGE = 'df_by_platform'
COUNTRY_NAMED_RANGE = 'df_by_country'